import React, { useEffect, useState } from 'react';
import { Shield, AlertTriangle, FileText, Loader2 } from 'lucide-react';
import './AuditView.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

const AuditView = ({ auditId }) => {
  const [audit, setAudit] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchAudit = async () => {
      try {
        const resp = await fetch(`${API_URL}/audits/${auditId}`);
        if (!resp.ok) {
          throw new Error('Audit not found or expired');
        }
        const data = await resp.json();
        setAudit(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchAudit();
  }, [auditId]);

  if (loading) {
    return (
      <div className="audit-view-center">
        <Loader2 size={48} className="spin text-lime" />
        <p>Loading audit report...</p>
      </div>
    );
  }

  if (error || !audit) {
    return (
      <div className="audit-view-center error-page">
        <AlertTriangle size={64} className="text-warning mb-4" />
        <h2>Audit Not Found</h2>
        <p>This audit has expired or the link is invalid.</p>
        <button className="btn btn-primary mt-6" onClick={() => window.location.href = '/'}>
          Start New Audit
        </button>
      </div>
    );
  }

  return (
    <div className="audit-view-container">
      <header className="audit-view-header">
        <div className="audit-brand">
          <Shield size={24} className="text-lime" />
          <h1>FairLens Audit Report</h1>
        </div>
        <div className="audit-meta">
          <span className="audit-id">ID: {auditId}</span>
          <span className="audit-date">{new Date(audit.timestamp).toLocaleString()}</span>
        </div>
      </header>

      <main className="audit-view-content">
        <div className="audit-card">
          <div className="audit-card-header">
            <FileText size={20} className="text-blue" />
            <h2>Full Audit Report</h2>
          </div>
          <div className="audit-card-body">
            {audit.report ? (
              <div className="markdown-content">
                {audit.report.split('\n').map((line, i) => {
                  if (line.startsWith('# ')) return <h1 key={i}>{line.slice(2)}</h1>;
                  if (line.startsWith('## ')) return <h2 key={i}>{line.slice(3)}</h2>;
                  if (line.startsWith('### ')) return <h3 key={i}>{line.slice(4)}</h3>;
                  if (line.startsWith('---')) return <hr key={i} />;
                  if (line.startsWith('- ')) return <li key={i}>{line.slice(2)}</li>;
                  if (line.startsWith('*')) return <p key={i} className="italic-text">{line.replace(/\*/g, '')}</p>;
                  if (line.match(/^[0-9]+\./)) return <li key={i}>{line}</li>;
                  if (line.trim() === '') return <br key={i} />;
                  return <p key={i}>{line}</p>;
                })}
              </div>
            ) : (
              <p className="text-muted">No text report available for this audit.</p>
            )}
          </div>
        </div>
      </main>

      <footer className="audit-view-footer">
        Generated by FairLens · Google Solution Challenge 2026
      </footer>
    </div>
  );
};

export default AuditView;
